export const metadata = {
  title: "Sanity Studio",
  description: "Generated by Sanity",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>{children}</body>
    </html>
  );
}
